### PR TITLE
Faces 2662

### PR DESCRIPTION
**Pull request by pcwhite**

### CODE REVIEW

**Comment by pcwhite** [comment]
@ngriffin7a, @vsingleton

**Comment by stiemannkj1** [comment]
@pcwhite, please format your code. Specifically `jsf-showcase-webapp/src/test/java/com/liferay/faces/test/showcase/select/SelectTester.java`. Also, I noticed a couple of references to the rendered checkboxes with `TODO`s. Please remove that code since it is not complete yet. I think in the future we will need to come up with a strategy to tackle the rendered checkboxes, but we can leave it out for now.

**Comment by stiemannkj1** [comment]
@pcwhite, feel free to update this PR or send a new one, whatever you want.

**Comment by stiemannkj1** [comment]
@pcwhite,

Aside from the DRY stuff we skyped about. Here were some other improvements that should be made:
- [ ] Please make sure that all the comments are correct and accurate. For example: https://github.com/stiemannkj1/liferay-faces-showcase/pull/3/files#diff-55962b264496aa43c1161ce20be09ee2R46. The comments were probably copy/pasted, and they do not reflect what the code is actually doing. Remember that the comments should be high-level documentation on **what** the code is doing or **why** the code is needed (not low-level info on **how** the code is doing something which is documented by the code itself).
- [ ] Some of the xpaths can be simplified. For example: `"(//div[@class='showcase-example-usage']/select/option)[1]"` can be changed to `"(select[contains(@id, 'select')]/option)[1]"`. This change would require that every select component has a `id` attribute (I think you already made sure of that in the current PR).
- [ ] The `modelValue` xpaths are inconsistent with the rest of the tests. For example, the input and output testers model value xpaths look like this:

```
protected static final String modelValue1Xpath = "(//span[contains(@id,':modelValue')])[1]";
```

However, the select model value xpaths look like this:

```
protected static final String modelValue1Xpath = "//div[@class='results-content']";
```

The select model value xpath could break if we change the name of that class. Since we want the tests to be robust and consistent, please make the select model value xpath the same as the other tests. To fix this inconsistency, you will need to fix the use cases themselves since the `id` is actually applied to the `ui:repeat` rather than a `span`:

```
<showcase:results label="#{i18n['model-value']}">
    <ui:repeat id="modelValue" value="#{selectManyModelBean.favoriteIds}" var="favoriteId">
        <h:outputText value="#{favoriteId}" />
        <br />
    </ui:repeat>
</showcase:results>
```

In order to fix this, you will need to change the above to:

```
<showcase:results label="#{i18n['model-value']}">
    <h:panelGroup id="modelValue">
        <ui:repeat value="#{selectManyModelBean.favoriteIds}" var="favoriteId">
            <h:outputText value="#{favoriteId}" /><br />
        </ui:repeat>
    </h:panelGroup>
</showcase:results>
```

Then you can change the model value xpath to use an `id` instead of a class.

Let me know if you have any questions,

\- Kyle

**Comment by pcwhite** [comment]
@ngriffin7a, @vsingleton, @stiemannkj1 
ready for code review

**Comment by stiemannkj1** [comment]
@pcwhite,
Just started reviewing.

\- Kyle

**Comment by stiemannkj1** [comment]
@pcwhite,
I will post the complete code review tomorrow. But for now, please:
1. Update your `liferay-faces-test-selenium` repo to get [my recent changes](https://github.com/ngriffin7a/liferay-faces-test-selenium/pull/10/files) (which this PR depends on).
2. Get my [PR changes](https://github.com/pcwhite/liferay-faces-showcase/pull/1):
   
   ```
   git fetch stiemannkj1
   ```
3. Checkout a temporary branch from `FACES-2662` (make sure to stash or commit whatever you are working on before doing this):
   
   ```
   git checkout FACES-2662 && git checkout -b temp
   ```
4. Merge https://github.com/pcwhite/liferay-faces-showcase/pull/1 into your `temp` branch:
   
   ```
   git merge changes-pcwhite_FACES-2662
   ```
5. Squash my changes into your commit:
   
   ```
   git reset HEAD~1 --soft && git commit -a --amend --no-edit
   ```
6. Compile your `temp` branch and re-run the tests to make sure that they run.

**Comment by stiemannkj1** [comment]
@pcwhite, 
Instead of following the above comment, you could just replace "`assertElementTextNotVisible`" with "`assertElementTextInvisible`" and remove `assertCheckboxNotChecked` lines. That might be easier. See my PR to you for an example of what I needed to change: https://github.com/pcwhite/liferay-faces-showcase/pull/1

**Comment by stiemannkj1** [comment]
@pcwhite

# Code Review
- [ ] Make sure all variables are [camel-case](https://en.wikipedia.org/wiki/CamelCase). [`selectmanycheckboxURL` is not camel-case](https://github.com/stiemannkj1/liferay-faces-showcase/pull/3/files#diff-0c609344ece5ed6627e79a69bd6fa51aR33) and should be changed to `selectManyCheckboxURL`.
- [ ] Try to distinguish between different examples when creating xpath and xpath variable names. Xpath should demonstrate whether checkbox or options are from the first example or the second one. [For example](https://github.com/stiemannkj1/liferay-faces-showcase/pull/3/files#diff-4864e92830ac8fc7daad98da60bf58faR50), `(//select[contains(@id, 'select')]/option)[8]` does not show that it is actually the third option of the second select. Here's the original:
  
  ```
  String option3Xpath2 = "(//select[contains(@id, 'select')]/option)[8]";
  ```
  
  Here's how it could be improved:
  
  ```
  String select2Option3Xpath = "(//select[contains(@id, 'select')][2]/option)[3]";
  ```

Before you attempt the below tasks, please chat with me on Skype so we can go over them.
- [ ] Add a `testSelectBooleanCheckbox(Browser browser, String checkbox1Xpath)` method and reduce repeated code in the `selectBooleanCheckbox` testers.
- [ ] The `selectManyCheckbox` testers still repeat too much. For example, [the `testManyCheckbox()` method](https://github.com/stiemannkj1/liferay-faces-showcase/pull/3/files#diff-bb75ec2f3f1f04f7a76e417dbeca21dcR35) could be made more general so that it could be used for **both** the first and second set of checkboxes. For example, instead of passing the answers to `testManyCheckbox()`, you could pass the checkbox set that you want to test:
  
  ```
  String selectManyCheckbox1Xpath = "//table[contains(@id, ':selectManyCheckbox')][1]"
  testManyCheckbox(browser, selectManyCheckbox1Xpath);
  ```
  
  Then, inside `testManyCheckbox()`, you could get the checkbox xpath like this:
  
  ```
  String checkbox3Xpath = "(" + selectManyCheckboxXpath + "//input[contains(@id, ':selectManyCheckbox:')])[3]";
  ```
  
  With those changes in mind, `runSelectManyCheckboxImmediateTest()` would look more like this:
  
  ```
  testManyCheckbox(browser, selectManyCheckbox1Xpath);
  SeleniumAssert.assertElementVisible(browser, immediateMessage1Xpath);
  testManyCheckbox(browser, selectManyCheckbox2Xpath);
  SeleniumAssert.assertElementVisible(browser, immediateMessage2Xpath);
  ```
  
  That would reduce some of the repeated code. This change would actually break the `runSelectManyCheckboxConversionTest()`, but that reveals another problem in that test (see below).
- [ ] `runSelectManyCheckboxConversionTest()` should not use the `testManyCheckbox()` method because it forces the calling code to understand the exact internals of `testManyCheckbox()`. Any code that calls `testManyCheckbox()` needs to know exactly which checkboxes it will check before calling it so that the parameters will be in the correct order and have the correct values. Instead `testManyCheckbox()` should stand on its own and be able to change what checkboxes it checks without breaking other tests. So `runSelectManyCheckboxConversionTest()` is a special case, and it should not use `testManyCheckbox()` because it forces `testManyCheckbox()` to expose its implementation.
- [ ] [`runSelectOneMenuDataModelTest1()` and `runSelectOneMenuDataModelTest2()` repeat each other](https://github.com/stiemannkj1/liferay-faces-showcase/pull/3/files#diff-8ab5981ab88862841f46fef9f244b755R59). Methods like this can either be turned into a single method or into one method which calls the other. Here's a simplified version of what I would expect instead:
  
  ```
  runSelectOneMenuDataModelTest() {
      Browser browser = Browser.getInstance();
      browser.waitForElementVisible(option1Xpath);
      testSelectOneMenu(browser, select1Xpath);
      testSelectOneMenu(browser, select2Xpath);        
  }
  ```
- [ ] When a string is only used once, you can just use a string literal. [For example](https://github.com/stiemannkj1/liferay-faces-showcase/pull/3/files#diff-1d862e148e0de4a88b065eae2c1261fdR56):
  
  ```
  String answer4 = "Jul 14, 1789 AD";
  SeleniumAssert.assertElementTextVisible(browser, modelValue1Xpath, answer4);
  ```
  
  Can be changed to:
  
  ```
  SeleniumAssert.assertElementTextVisible(browser, modelValue1Xpath, "Jul 14, 1789 AD");
  ```

\- Kyle

**Comment by stiemannkj1** [comment]
Re-sent as https://github.com/liferay/liferay-faces-showcase/pull/7. See code review commit here: https://github.com/liferay/liferay-faces-showcase/pull/7/commits/5d32f93e9e8641eb0e7f31312efbb53f9464a97c
I also had to make one other change to make the Input tests consistent: https://github.com/liferay/liferay-faces-showcase/pull/7/commits/c0f6a42377fa307bd4df0f60ce30b96563d1459c

**Pull request closed without merging**
