### PR TITLE
Faces 2955 3.x

### PR DESCRIPTION
**Pull request by pcwhite**

### CODE REVIEW

**Comment by stiemannkj1** [comment]
@pcwhite, please also assert the column header values as we discussed on skype.

**Comment by stiemannkj1** [comment]
@pcwhite, no need to create variables within this class (since the strings are only used once). Please remove the variables and pass the string literals to the assertion methods. For example change this:

```
String dataTableHeaderXpath =
    "(//div[contains(@class,'showcase-example-usage')])/table/*/tr/th[contains(.,'Customers')]";

/* ... */

SeleniumAssert.assertElementVisible(browser, dataTableHeaderXpath);
```

Into this:

```
SeleniumAssert.assertElementVisible(browser,
    "(//div[contains(@class,'showcase-example-usage')])/table/*/tr/th[contains(.,'Customers')]");
```

Please comment on this PR when you have updated your commit.

**Comment by pcwhite** [comment]
updated!

**Comment by stiemannkj1** [comment]
@pcwhite, merged and sent to Neil as https://github.com/liferay/liferay-faces-showcase/pull/34. **Note:** I made the xpaths more specific in [my code review commit](https://github.com/liferay/liferay-faces-showcase/pull/34/commits/4c39a767677664b3cf5a8df24b064103221e4a11) in order to ensure that the headers are included in the table header, the footer is included in the table footer, and the table content is included in the table body.

**Pull request closed without merging**
